-- create table students(
-- id BIGSERIAL PRIMARY KEY,
-- first_name varchar(50),
-- last_name varchar(50),
-- birth_date date
-- );
-- insert into students(first_name,last_name,birth_date) Values('Marc', 'Benichou', '1998-11-02'),('Yoan', 'Cohen', '2010-12-03'),('Lea', 'Benichou', '1987-07-27'),('Amelia', 'Dux', '1996-04-07'),('David', 'Grez', '2003-06-14'),('Omer', 'Simpson', '1980-10-03');
-- select * from students;
-- select last_name,first_name from students;
--SELECT first_name, last_name FROM students WHERE id = 2;
--SELECT first_name, last_name FROM students WHERE first_name = 'Marc' AND last_name = 'Benichou';
--SELECT first_name, last_name FROM students WHERE first_name = 'Marc' OR last_name = 'Benichou';
--SELECT first_name, last_name FROM students WHERE first_name ILIKE '%a%';
--SELECT first_name, last_name FROM students WHERE first_name ILIKE 'a%';
--SELECT first_name, last_name FROM students WHERE first_name ILIKE '%a';
--SELECT first_name, last_name FROM students WHERE first_name ILIKE '%a%';
--SELECT * from students where id = 1 and id = 3;
-- SELECT *
-- FROM students
-- WHERE birth_date >= '2000-01-01';


